### ISSUE TITLE
Fails to stream via Music Assistant

### ISSUE THREAD

**Issue by Davis8483** [Frank-Friemel/ShairportQt#10]
Heyo, I've been at this a while now. When running the app my desktop shows up in my Music Assistant interface although when I try to initiate playback no sound is produced. The only change in the app(ShairportQt) interface is the media control buttons greying out. Neither cover art or other track info is shown.

I've already tried completely disabling my firewall and restarting my home assistant server. Still, to no avail. Any help would be greatly appreciated. 

![image](https://github.com/user-attachments/assets/1ff9bb1f-ba80-40cf-9777-9f5a3486d559)

**Comment by Frank-Friemel** [comment]
You are right. This has to be fixed on my side. Coming soon ...

**Comment by Frank-Friemel** [comment]
Should be fixed with version 1.0.0.3. For me it works now either with or without encryption

**Comment by Davis8483** [comment]
I'll test when I get back from vacation, thanks!

**Comment by Davis8483** [comment]
The fix works for me as well!!!
