### ISSUE TITLE
[Windows 10] service appears to respond but music still plays on iphone

### ISSUE THREAD

**Issue by mbourgon** [Frank-Friemel/ShairportQt#2]
[ShairportQt.-.Copy.log](https://github.com/user-attachments/files/17270060/ShairportQt.-.Copy.log)

Windows 10.0.19045, build 19045.4894, aka Windows 10 Enterprise N 22H2          

Downloaded version yesterday (1.0.0.1)
unzipped into new folder
ran, no password set.
tried to connect from iphone. Says it connects (phone shows speaker), but music continues to play from phone, not Windows.
Log attached

Additionally (probably need a new ticket) if I try to close the app while "playing" to it, app hangs.
Thank you!

**Comment by Frank-Friemel** [comment]
This seems to be a firewall issue. Please try to type „wf.msc“ in a cmd box. Then add a rule for ShairportQt.exe application which allows all in and out traffic for UDP and TCP. Then retry to connect

**Comment by mbourgon** [comment]
Well, that was certainly weird - I went looking today to do that, and I saw there were 2 rules, one for UDP and one for TCP, set like you suggested, and it now works. A cursory search of Event Viewer doesn't have anything about it that I can easily find, so I'm unsure how it got created or why it didn't work originally, but it does now. Thanks!
