### ISSUE TITLE
Always using the system-default sound card

### ISSUE THREAD

**Issue by Alxj24** [Frank-Friemel/ShairportQt#5]
even if you use the option of other sounds card, the ShairportQT always address the sound to system-default sound card. The issue is not present in previous deprecated versions.

**Comment by Frank-Friemel** [comment]
Can not reproduce. Which OS are you using? And please do this:

- Switch to the sound-device in question
- enable "log to file" in the same options-dialog
- close options-dialog with "ok"
- exit ShairportQt
- start ShairportQt again
- stream some sound to ShairportQt for a few seconds
- exit ShairportQt

Aferwards, there should be a log file "ShairportQt.log" in your home-folder. Please provide that log-file here. You may
disable the option "log to file" when you're done.

Thanks

**Comment by Alxj24** [comment]
[ShairportQt.log](https://github.com/user-attachments/files/18036740/ShairportQt.log)
![screen](https://github.com/user-attachments/assets/f3257070-3c9e-4ad2-bcd1-d0e12afff9e2)

**Comment by Frank-Friemel** [comment]
Right, there's a bug in the code. I'll fix it

**Comment by Alxj24** [comment]
Happy to contribute

Thanks
Alessandro


Il giorno ven 6 dic 2024 alle 15:30 Frank Friemel ***@***.***>
ha scritto:

**Comment by Frank-Friemel** [comment]
A new release is available [1.0.0.2](https://github.com/Frank-Friemel/ShairportQt/releases). Please test, if the issue is fixed. Thanks
