### ISSUE TITLE
Windows Minimize to Tray

### ISSUE THREAD

**Issue by albino1** [Frank-Friemel/ShairportQt#6]
When you click minimize in Shairport4w it minimizes to the tray, but with ShairportQt when I click minimize it just does a normal Windows minimize to the task bar.  If I hit X then it exits completely.  It starts in the tray when Windows boots, but if you interact with it then it can't be minimized back to the tray.  Would it be possible to get the previous behavior back? 

OS: Windows 10
ShairportQt: 1.0.0.1

**Comment by albino1** [comment]
That does work, thanks.

Out of curiosity, why not make minimize to tray the default?  I can't imagine anybody wants to intentionally run ShairportQt full time in the foreground, especially after having run Shairport4w minimized for years.

**Comment by Frank-Friemel** [comment]
This is a GUI application. I guess most users would expect something to appear on their Desktop, when they start off

**Comment by albino1** [comment]
FWIW, I'm fairly techy, and it would have never occurred to me to double-click on a tray icon in order to minimize something to the tray.  Even though I now have a solution, I still think an option in settings would make the most sense for the majority of people.

Thanks for continuing to maintain this software, I use it every day.

**Comment by Davis8483** [comment]
I added a shortcut to the startup folder. How would go about starting it minimized to the system tray?

**Comment by maboroshin** [comment]
Duplicate : https://github.com/Frank-Friemel/ShairportQt/issues/15
